name: Deploy React to EC2 using S3 and CodeDeploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21.1.0'

    - name: Create .env file
      run: |
        - name: Create .env file
      run: |
        echo "REACT_APP_GOOGLE_CLIENTID=${{ secrets.REACT_APP_GOOGLE_CLIENTID }}" >> .env
        echo "REACT_APP_KAKAO_REST_API_KEY=${{ secrets.REACT_APP_KAKAO_REST_API_KEY }}" >> .env
        echo "REACT_APP_SERVICE_KEY=${{ secrets.REACT_APP_SERVICE_KEY }}" >> .env
        echo "REACT_APP_S_SERVICE_KEY=${{ secrets.REACT_APP_S_SERVICE_KEY }}" >> .env

    - name: Install dependencies
      run: npm install

    - name: Build React app
      run: npm run build

    - name: Zip build folder and appspec
      run: zip -r react-app.zip build appspec.yml scripts/

    - name: Upload the ZIP file to S3
      run: aws s3 cp react-app.zip s3://ondegande-s3-build/

    - name: Deploy to CodeDeploy
      run: |
        aws deploy create-deployment \
          --application-name ondegande \
          --deployment-group-name ondegande-group \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --description "Deploying from GitHub Actions" \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=ondegande-s3-build,key=react-app.zip,bundleType=zip